# Generated by Django 5.0 on 2023-12-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0001_initial'),
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='events',
            field=models.ManyToManyField(related_name='profiles', to='event_manager.event'),
        ),
    ]
