# Generated by Django 3.2.23 on 2024-01-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0002_userprofile_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthday_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
