# Generated by Django 3.2.23 on 2024-01-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0002_auto_20240119_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
